-- Sullivan Fit — Exercise Library seed data
-- Paste this into the Supabase SQL Editor and run it.
-- Safe to re-run: deletes and re-inserts all exercises.

DELETE FROM exercises;

INSERT INTO exercises (name, day, category) VALUES
  ('Bench Press – Flat Barbell', 'D1 – Push', 'Resistance'),
  ('Bench Press – Close-Grip Barbell', 'D1 – Push', 'Resistance'),
  ('Bench Press – Incline Barbell', 'D1 – Push', 'Resistance'),
  ('Incline DB Press – 30–45°', 'D1 – Push', 'Resistance'),
  ('Incline DB Press – Neutral Grip', 'D1 – Push', 'Resistance'),
  ('DB Bench Press – Flat', 'D4 – Push (Alt)', 'Resistance'),
  ('Decline Press – Barbell', 'Optional', 'Resistance'),
  ('Push-Up – Standard', 'Bodyweight', 'Calisthenics'),
  ('Push-Up – Band-Assisted', 'D1 – Push', 'Calisthenics'),
  ('Dips – Chest (forward lean)', 'D4 – Push (Alt)', 'Calisthenics'),
  ('Dips – Triceps (upright)', 'D4 – Push (Alt)', 'Calisthenics'),
  ('Seated DB Shoulder Press – Standard', 'D1 – Push', 'Resistance'),
  ('Arnold Press – DB', 'D4 – Push (Alt)', 'Resistance'),
  ('Smith Machine Shoulder Press – Seated', 'D1 – Push (Alt)', 'Resistance'),
  ('Lateral Raise – DB', 'D1 – Push', 'Resistance'),
  ('Lateral Raise – Cable', 'D1 – Push', 'Resistance'),
  ('Lateral Raise – Banded', 'D1 – Push', 'Resistance'),
  ('Front Raise – DB', 'Accessory', 'Resistance'),
  ('Face Pull – Cable', 'D4 – Pull', 'Resistance'),
  ('Rear Delt Fly – DB or Pec Deck', 'D4 – Pull', 'Resistance'),
  ('Triceps Pushdown – Rope or Bar – Cable', 'D1 – Push', 'Resistance'),
  ('Overhead Triceps Extension – Cable or DB', 'D1 – Push', 'Resistance'),
  ('Overhead Triceps Extension – DB Single Arm', 'Accessory', 'Resistance'),
  ('Skull Crusher – EZ Bar', 'Accessory', 'Resistance'),
  ('Pull-Up – Weighted', 'D3/D4', 'Calisthenics / Resistance'),
  ('Pull-Up – Assisted (Band or Machine)', 'D3/D4', 'Calisthenics'),
  ('Pull-Up – Chin-Up (supinated)', 'D3/D4', 'Calisthenics'),
  ('Lat Pulldown – Standard Wide Grip', 'D4 – Pull', 'Resistance'),
  ('Lat Pulldown – Close Grip', 'D4 – Pull', 'Resistance'),
  ('Single Arm Lat Pulldown – Cable', 'D4 – Pull', 'Resistance'),
  ('Barbell Row – Bent Over', 'D4 – Pull', 'Resistance'),
  ('Barbell Row – Pendlay Row', 'D4 – Pull', 'Resistance'),
  ('Cable Row – Seated', 'D4 – Pull', 'Resistance'),
  ('Single Arm DB Row – Chest Supported', 'D4 – Pull', 'Resistance'),
  ('Single Arm DB Row – Kroc Row', 'D4 – Pull', 'Resistance'),
  ('Trap Bar Deadlift – Standard', 'Accessory', 'Resistance'),
  ('EZ Bar Curl – Standard', 'D4 – Pull', 'Resistance'),
  ('DB Curl – Standard', 'D4 – Pull', 'Resistance'),
  ('Hammer Curl – DB', 'D4 – Pull', 'Resistance'),
  ('Rope Hammer Curl – Cable', 'D4 – Pull (Alt)', 'Resistance'),
  ('Concentration Curl – DB', 'Accessory', 'Resistance'),
  ('Preacher Curl – EZ Bar or DB', 'Accessory', 'Resistance'),
  ('Pendulum Squat – Standard', 'D2 – Quads/Glutes', 'Resistance'),
  ('Back Squat – Barbell High Bar', 'D2/D5', 'Resistance'),
  ('Back Squat – Low Bar', 'D2/D5', 'Resistance'),
  ('Front Squat – Barbell', 'D2 – Quads/Glutes', 'Resistance'),
  ('Belt Squat – Machine or Cable', 'D2 – Quads/Glutes', 'Resistance'),
  ('Box Squat – Barbell', 'Accessory', 'Resistance'),
  ('Leg Press – Standard Bilateral', 'D2 – Quads/Glutes', 'Resistance'),
  ('Leg Press – High Foot Placement', 'D2 – Quads/Glutes', 'Resistance'),
  ('Leg Press – Single Leg', 'Accessory', 'Resistance'),
  ('Leg Extension – Machine', 'D2 – Quads/Glutes', 'Resistance'),
  ('Bulgarian Split Squat – DB', 'D2 – Quads/Glutes', 'Resistance'),
  ('Walking Lunge – DB or Bodyweight', 'D2 – Quads/Glutes', 'Resistance / Calisthenics'),
  ('Reverse Lunge – DB or Barbell', 'Accessory', 'Resistance'),
  ('Step-Up – Weighted', 'D5 – Ham/Glutes', 'Resistance'),
  ('Box Jump – Plyometric', 'D2 – Quads/Glutes (contrast)', 'Plyometric'),
  ('Broad Jump – Plyometric', 'D5 – Ham/Glutes (contrast)', 'Plyometric'),
  ('Romanian Deadlift – Barbell', 'D5 – Ham/Glutes', 'Resistance'),
  ('Romanian Deadlift – B-Stance (Single Leg)', 'D5 – Ham/Glutes', 'Resistance'),
  ('Romanian Deadlift – DB', 'D5 – Ham/Glutes', 'Resistance'),
  ('Barbell Deadlift – Conventional', 'D3 – Posterior Chain', 'Resistance'),
  ('Barbell Deadlift – Sumo', 'D3 – Posterior Chain', 'Resistance'),
  ('Hip Thrust – Barbell', 'D5 – Ham/Glutes', 'Resistance'),
  ('Hip Thrust – Single Leg', 'Accessory', 'Resistance'),
  ('Glute Bridge – Barbell or Bodyweight', 'Accessory', 'Resistance / Calisthenics'),
  ('Hamstring Curl – Lying Machine', 'D3/D5', 'Resistance'),
  ('Hamstring Curl – Seated Machine', 'D3/D5', 'Resistance'),
  ('Nordic Hamstring Curl – Bodyweight', 'Accessory', 'Calisthenics'),
  ('Adductor Machine – Seated', 'D5 – Ham/Glutes', 'Resistance'),
  ('Abductor Machine – Seated', 'Accessory', 'Resistance'),
  ('Cable Pull-Through – Low Cable', 'D3 – Posterior Chain', 'Resistance'),
  ('Good Morning – Barbell', 'Accessory', 'Resistance'),
  ('Calf Raise – Standing – Weighted', 'D2 – Quads/Glutes', 'Resistance'),
  ('Calf Raise – Seated', 'Accessory', 'Resistance'),
  ('Calf Raise – Single Leg', 'Accessory', 'Resistance / Calisthenics'),
  ('Weighted Decline Sit-Up – Plate', 'Core (Rotating)', 'Resistance'),
  ('Cable Crunch – Rope Attachment', 'Core (Rotating)', 'Resistance'),
  ('Cable Woodchop – High-to-Low', 'Core (Rotating)', 'Resistance'),
  ('Cable Woodchop – Low-to-High', 'Core (Rotating)', 'Resistance'),
  ('Plank – Standard', 'Core (Rotating)', 'Calisthenics'),
  ('Ab Wheel Rollout – Kneeling or Standing', 'Core', 'Resistance / Calisthenics'),
  ('Hanging Leg Raise – Straight or Bent Knee', 'Core', 'Calisthenics'),
  ('Pallof Press – Cable', 'Core', 'Resistance'),
  ('Kettlebell Swing – Two-Handed', 'D3 – Posterior Chain', 'Resistance / HIIT'),
  ('Kettlebell Swing – Single Arm', 'D3 – Posterior Chain', 'Resistance / HIIT'),
  ('Med Ball Slam – Standard', 'D3/D4 – Contrast', 'Plyometric'),
  ('Split Stance Med Ball Slam – Staggered', 'D3 – Contrast', 'Plyometric'),
  ('Sled Push – Standard', 'D3 – Posterior Chain', 'HIIT / Resistance'),
  ('Sled Pull – Standard', 'D3 – Posterior Chain', 'HIIT / Resistance'),
  ('Farmer Carry – DB or Trap Bar', 'D3 – Hotel Finisher', 'HIIT / Resistance'),
  ('Band Pull-Apart – Standard', 'Pre-Activation – Push/Pull', 'Mobility / Resistance'),
  ('Band External Rotation – Side-lying or Standing', 'Pre-Activation – Push/Pull', 'Mobility / Resistance'),
  ('Y-T-W Raise – DB or Bodyweight', 'Pre-Activation – Push/Pull', 'Mobility / Resistance'),
  ('Serratus Punch – Cable or DB', 'Pre-Activation – Push/Pull', 'Mobility / Resistance'),
  ('Banded Monster Walk – Side to Side', 'Warm-Up – Lower', 'Mobility / Resistance'),
  ('Foam Roll – General / Quads / Glutes', 'Warm-Up', 'Mobility'),
  ('Hip Flexor Stretch – Kneeling', 'Warm-Up – Lower', 'Mobility'),
  ('Dead Hang – Bar', 'Warm-Up – Pull', 'Mobility'),
  ('Cat-Cow – Floor', 'Warm-Up', 'Mobility'),
  ('Running – Steady State / Zone 2', 'Cardio', 'Cardio'),
  ('Cycling – Stationary or Road', 'Cardio', 'Cardio'),
  ('Row Erg – Machine', 'Cardio / HIIT', 'Cardio / HIIT'),
  ('Stair Climber – Machine', 'Cardio', 'Cardio'),
  ('Jump Rope – Standard', 'Cardio / HIIT', 'HIIT / Cardio');
